spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/sys
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8081
